import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { pathToFileURL } from 'node:url';
import { operation, planDigest, redact, requireConfirmation } from '../dist/domain/operation.js';
import { gitFlowInit, gitFlowStatus, gitFlowStart, gitFlowFinish } from '../dist/workflow.js';
import { withOperationLock, createJournal, listJournals, loadJournal, saveJournal } from '../dist/operations/journal.js';
import { presetConfig, detectProject, migrateConfig, validateConfigFile } from '../dist/onboarding.js';
import { planPackagePublish, publishPackage } from '../dist/packages/publisher.js';
import { releasePlan } from '../dist/release/planner.js';
import { applyMonorepoVersions, detectWorkspaces, impactedPackages, monorepoReleasePlan } from '../dist/monorepo.js';
import { providerCapabilities, repositoryCoordinates } from '../dist/providers.js';
import { createChangeRequest, inspectChangeRequest, mergeChangeRequest, closeChangeRequest, createProviderRelease, publishReviewComment } from '../dist/providers.js';
import { executeRelease, resumeRelease } from '../dist/release/executor.js';
import { projectTree } from '../dist/projection.js';
import { loadPlugin } from '../dist/plugins.js';
import { runScanner } from '../dist/scanners.js';
import { generateReleaseNotes } from '../dist/release/notes.js';
import { reviewRepo } from '../dist/review/reviewer.js';
import { generateSupplyChainArtifacts } from '../dist/artifacts.js';
import { HeadbangApplication } from '../dist/application.js';

const exec=promisify(execFile);
async function git(repo,...args){return exec('git',['-C',repo,...args]);}
async function initRepo(prefix='headbang-v2-'){const base=await mkdtemp(join(tmpdir(),prefix)),repo=join(base,'repo');await mkdir(repo);await exec('git',['init','-b','main',repo]);await git(repo,'config','user.name','Test');await git(repo,'config','user.email','test@example.com');await writeFile(join(repo,'README.md'),'# test\n');await git(repo,'add','-A');await git(repo,'commit','-m','feat: initial');return{base,repo};}
const flowProfile={remote:'origin',permissions:{flow:true},branch:{strategy:'git-flow',main:'main',develop:'develop'}};

test('stable operation envelope, digest confirmation, and redaction',()=>{const plan={b:2,a:1,token:'npm_secret_value'};const digest=planDigest(plan);assert.equal(digest,planDigest({a:1,b:2,token:'different'}));assert.throws(()=>requireConfirmation(plan,'wrong'),/Confirmation required/);assert.equal(requireConfirmation(plan,digest),digest);assert.equal(redact(plan).token,'[REDACTED]');const result=operation({ok:true});assert.equal(result.success,true);assert.deepEqual(result.errors,[]);});

test('native flow init restores missing develop without switching or moving existing history',async()=>{const{base,repo}=await initRepo('headbang-flow-init-');try{const before=(await git(repo,'rev-parse','main')).stdout.trim();const first=await gitFlowInit(repo,flowProfile);assert.equal(first.created,true);assert.equal(first.sourceSha,before);assert.equal((await git(repo,'branch','--show-current')).stdout.trim(),'main');const status=await gitFlowStatus(repo,flowProfile);assert.equal(status.ready,true);await git(repo,'checkout','-b','other');await writeFile(join(repo,'other.txt'),'x\n');await git(repo,'add','-A');await git(repo,'commit','-m','feat: other');const developBefore=(await git(repo,'rev-parse','develop')).stdout.trim();const second=await gitFlowInit(repo,flowProfile);assert.equal(second.status,'already-completed');assert.equal((await git(repo,'rev-parse','develop')).stdout.trim(),developBefore);assert.equal((await git(repo,'branch','--show-current')).stdout.trim(),'other');}finally{await rm(base,{recursive:true,force:true});}});

test('flow init rejects dirty tree and missing main without mutation',async()=>{const{base,repo}=await initRepo('headbang-flow-guard-');try{await writeFile(join(repo,'dirty.txt'),'x');await assert.rejects(gitFlowInit(repo,flowProfile),/clean/);await rm(join(repo,'dirty.txt'));await assert.rejects(gitFlowInit(repo,{...flowProfile,branch:{...flowProfile.branch,main:'missing'}}),/does not exist/);assert.equal((await git(repo,'show-ref','--verify','--quiet','refs/heads/develop').then(()=>true).catch(()=>false)),false);}finally{await rm(base,{recursive:true,force:true});}});

test('operation lock excludes concurrent mutation and journals are redacted',async()=>{const{base,repo}=await initRepo('headbang-lock-');try{let release;const gate=new Promise(resolve=>{release=resolve;});const first=withOperationLock(repo,'first',async()=>gate);await new Promise(resolve=>setTimeout(resolve,50));await assert.rejects(withOperationLock(repo,'second',async()=>true),/Another HEADBANG mutation/);release();await first;await createJournal(repo,'test',['one'],{token:'ghp_secret'});const journals=await listJournals(repo);assert.equal(journals.length,1);assert.equal(journals[0].context.token,'[REDACTED]');}finally{await rm(base,{recursive:true,force:true});}});

test('governed native Git plans exact arguments and executes cherry-pick once',async()=>{const{base,repo}=await initRepo('headbang-git-');try{await git(repo,'checkout','-b','topic');await writeFile(join(repo,'picked.txt'),'picked\n');await git(repo,'add','picked.txt');await git(repo,'commit','-m','feat: pick me');const sha=(await git(repo,'rev-parse','HEAD')).stdout.trim();await git(repo,'checkout','main');await writeFile(join(repo,'.headbang.json'),JSON.stringify({version:2,defaultProfile:'allowed',profiles:{allowed:{remote:'origin',permissions:{git:true}},denied:{remote:'origin',permissions:{git:false}}}}));const app=new HeadbangApplication();await assert.rejects(app.gitPlan(repo,'denied',['status']),/does not permit 'git'/);await assert.rejects(app.gitPlan(repo,'allowed',[]),/at least one/);const plan=await app.gitPlan(repo,'allowed',['cherry-pick',sha]);assert.equal(plan.status,'planned');assert.deepEqual(plan.data.args,['cherry-pick',sha]);await assert.rejects(app.gitExecute(repo,'allowed',['branch','unexpected'],plan.planDigest),/Confirmation required/);assert.equal((await git(repo,'show-ref','--verify','--quiet','refs/heads/unexpected').then(()=>true).catch(()=>false)),false);const result=await app.gitExecute(repo,'allowed',['cherry-pick',sha],plan.planDigest);assert.equal(result.status,'completed');assert.equal((await readFile(join(repo,'picked.txt'),'utf8')).trim(),'picked');assert.ok((await listJournals(repo)).some(item=>item.type==='git'&&item.status==='completed'));}finally{await rm(base,{recursive:true,force:true});}});

test('configured change request pushes its branch and opens a GitHub pull request',async()=>{const{base,repo}=await initRepo('headbang-pr-'),bare=join(base,'remote.git');const previousFetch=globalThis.fetch,previousToken=process.env.GITHUB_TOKEN;process.env.GITHUB_TOKEN='test-token';try{await exec('git',['init','--bare',bare]);const url='https://github.com/owner/repo.git';await git(repo,'config',`url.${pathToFileURL(bare).href}.pushInsteadOf`,url);await git(repo,'remote','add','origin',url);await git(repo,'checkout','-b','feature/pull-request');await writeFile(join(repo,'.headbang.json'),JSON.stringify({version:2,defaultProfile:'origin',profiles:{origin:{remote:'origin',provider:'github',permissions:{createPr:true},branch:{strategy:'github-flow',main:'main'},changeRequest:{enabled:true,target:'main'}}}}));const calls=[];globalThis.fetch=async(request,options={})=>{calls.push({url:String(request),method:options.method});if(String(request).endsWith('/branches/main/protection'))return new Response('{}',{status:404});return new Response(JSON.stringify({html_url:'https://github.com/owner/repo/pull/1'}),{status:201,headers:{'content-type':'application/json'}});};const app=new HeadbangApplication(),input={title:'Repository control'};const plan=await app.changePlan(repo,'origin',input),created=await app.changeCreate(repo,'origin',{...input,confirmation:plan.planDigest});assert.equal(created.data.html_url,'https://github.com/owner/repo/pull/1');assert.ok((await exec('git',['--git-dir',bare,'show-ref','--verify','refs/heads/feature/pull-request'])).stdout);assert.equal(calls.filter(call=>call.method==='POST').length,1);}finally{globalThis.fetch=previousFetch;if(previousToken===undefined)delete process.env.GITHUB_TOKEN;else process.env.GITHUB_TOKEN=previousToken;await rm(base,{recursive:true,force:true});}});

test('native Git confirmation binds repository state and supports unborn repositories',async()=>{
  const{base,repo}=await initRepo('headbang-git-state-'),config={version:2,defaultProfile:'allowed',profiles:{allowed:{remote:'origin',permissions:{git:true}},other:{remote:'origin',permissions:{git:false}}}},app=new HeadbangApplication();
  try{
    await writeFile(join(repo,'.headbang.json'),JSON.stringify(config));
    await assert.rejects(app.gitPlan(repo,'allowed',['-C','..','status']),/redirection/);
    await assert.rejects(app.gitPlan(repo,'allowed',['--git-dir=../other','status']),/redirection/);
    const secretA=await app.gitPlan(repo,'allowed',['remote','set-url','origin','https://user:ghp_one@example.com/repo.git']),secretB=await app.gitPlan(repo,'allowed',['remote','set-url','origin','https://user:ghp_two@example.com/repo.git']);assert.notEqual(secretA.planDigest,secretB.planDigest);assert.equal(secretA.data.args[3],'[REDACTED]');
    const branchPlan=await app.gitPlan(repo,'allowed',['branch','stale-branch']);await git(repo,'checkout','-b','same-sha');await assert.rejects(app.gitExecute(repo,'allowed',['branch','stale-branch'],branchPlan.planDigest),/Confirmation required/);await git(repo,'checkout','main');
    const configPlan=await app.gitPlan(repo,'allowed',['branch','stale-config']);await writeFile(join(repo,'.headbang.json'),JSON.stringify({...config,profiles:{...config.profiles,other:{remote:'origin',permissions:{git:true}}}}));await assert.rejects(app.gitExecute(repo,'allowed',['branch','stale-config'],configPlan.planDigest),/Confirmation required/);
    const headPlan=await app.gitPlan(repo,'allowed',['branch','stale-head']);await writeFile(join(repo,'state.txt'),'changed\n');await git(repo,'add','state.txt');await git(repo,'commit','-m','test: move head');await assert.rejects(app.gitExecute(repo,'allowed',['branch','stale-head'],headPlan.planDigest),/Confirmation required/);
    const clone=join(base,'clone');await exec('git',['clone',repo,clone]);await writeFile(join(clone,'.headbang.json'),await readFile(join(repo,'.headbang.json'),'utf8'));const repoPlan=await app.gitPlan(repo,'allowed',['branch','wrong-repo']);await assert.rejects(app.gitExecute(clone,'allowed',['branch','wrong-repo'],repoPlan.planDigest),/Confirmation required/);
    const unborn=join(base,'unborn');await exec('git',['init','-b','main',unborn]);await writeFile(join(unborn,'.headbang.json'),JSON.stringify(config));assert.equal((await app.gitPlan(unborn,'allowed',['status'])).data.sourceSha,null);
  }finally{await rm(base,{recursive:true,force:true});}
});

test('failed native Git execution rejects and records a failed journal',async()=>{
  const{base,repo}=await initRepo('headbang-git-failure-');
  try{
    await writeFile(join(repo,'.headbang.json'),JSON.stringify({version:2,defaultProfile:'allowed',profiles:{allowed:{remote:'origin',permissions:{git:true}}}}));await git(repo,'checkout','-b','conflict-source');await writeFile(join(repo,'README.md'),'source\n');await git(repo,'add','README.md');await git(repo,'commit','-m','test: source conflict');const sha=(await git(repo,'rev-parse','HEAD')).stdout.trim();await git(repo,'checkout','main');await writeFile(join(repo,'README.md'),'target\n');await git(repo,'add','README.md');await git(repo,'commit','-m','test: target conflict');const app=new HeadbangApplication(),plan=await app.gitPlan(repo,'allowed',['cherry-pick',sha]);await assert.rejects(app.gitExecute(repo,'allowed',['cherry-pick',sha],plan.planDigest),/CONFLICT|cherry-pick/i);assert.ok((await listJournals(repo)).some(item=>item.type==='git'&&item.status==='failed'));assert.ok((await git(repo,'rev-parse','--verify','CHERRY_PICK_HEAD')).stdout);
  }finally{await git(repo,'cherry-pick','--abort').catch(()=>{});await rm(base,{recursive:true,force:true});}
});

test('change-request confirmation binds the source commit',async()=>{
  const{base,repo}=await initRepo('headbang-pr-state-');const previousFetch=globalThis.fetch,previousToken=process.env.GITHUB_TOKEN;process.env.GITHUB_TOKEN='test-token';
  try{
    await git(repo,'remote','add','origin','https://github.com/owner/repo.git');await git(repo,'checkout','-b','feature/source-state');await writeFile(join(repo,'.headbang.json'),JSON.stringify({version:2,defaultProfile:'origin',profiles:{origin:{remote:'origin',provider:'github',permissions:{createPr:true},branch:{strategy:'github-flow',main:'main'},changeRequest:{enabled:true,target:'main'}}}}));globalThis.fetch=async()=>new Response('{}',{status:404});const app=new HeadbangApplication(),input={title:'Bind source'},plan=await app.changePlan(repo,'origin',input);await writeFile(join(repo,'after-plan.txt'),'new commit\n');await git(repo,'add','after-plan.txt');await git(repo,'commit','-m','test: move source');await assert.rejects(app.changeCreate(repo,'origin',{...input,confirmation:plan.planDigest}),/Confirmation required/);
  }finally{globalThis.fetch=previousFetch;if(previousToken===undefined)delete process.env.GITHUB_TOKEN;else process.env.GITHUB_TOKEN=previousToken;await rm(base,{recursive:true,force:true});}
});

test('presets, project detection, and backup-safe config migration',async()=>{const{base,repo}=await initRepo('headbang-init-');try{await writeFile(join(repo,'package.json'),JSON.stringify({scripts:{test:'node --test'},workspaces:['packages/*']},null,2));await writeFile(join(repo,'package-lock.json'),'{}');const detected=await detectProject(repo);assert.ok(detected.packageManagers.includes('npm'));assert.ok(detected.scripts.includes('test'));assert.equal(detected.monorepo,true);assert.equal(presetConfig('github-flow').profiles.origin.branch.strategy,'github-flow');await writeFile(join(repo,'.headbang.json'),JSON.stringify({version:1,profiles:{origin:{remote:'origin'}}}));const migrated=await migrateConfig(repo,true);assert.equal(migrated.status,'completed');assert.equal((await validateConfigFile(repo)).valid,true);assert.equal(JSON.parse(await readFile(join(repo,'.headbang.json'),'utf8')).version,2);assert.ok(await readFile(`${join(repo,'.headbang.json')}.v1.bak`,'utf8'));}finally{await rm(base,{recursive:true,force:true});}});

test('package and release plans are immutable, opt-in, and offline-safe',async()=>{const{base,repo}=await initRepo('headbang-plan-');const previous=process.env.HEADBANG_OFFLINE;process.env.HEADBANG_OFFLINE='1';try{await writeFile(join(repo,'package.json'),JSON.stringify({name:'test-package-never-publish',version:'1.0.0'},null,2));const profile={remote:'origin',permissions:{release:true,push:true,publishPackage:true},branch:{strategy:'trunk',main:'main'},release:{enabled:true,tagPrefix:'v'},packagePublish:{enabled:true,publisher:'npm',access:'public'}};const config={version:2,defaultProfile:'release',profiles:{release:profile}};const packagePlan=await planPackagePublish(repo,profile);assert.equal(packagePlan.status,'planned');assert.equal(packagePlan.data.alreadyPublished,null);assert.ok(packagePlan.planDigest);const plan=await releasePlan(repo,'2.0.0','release',profile,config);assert.equal(plan.data.proposedVersion,'2.0.0');assert.equal(plan.data.tag,'v2.0.0');assert.ok(plan.data.permissionsRequired.includes('publishPackage'));assert.ok(plan.planDigest);}finally{if(previous===undefined)delete process.env.HEADBANG_OFFLINE;else process.env.HEADBANG_OFFLINE=previous;await rm(base,{recursive:true,force:true});}});

test('workspace impact includes dependants and provider capabilities are explicit',async()=>{const{base,repo}=await initRepo('headbang-workspace-');try{await mkdir(join(repo,'packages','a'),{recursive:true});await mkdir(join(repo,'packages','b'),{recursive:true});await writeFile(join(repo,'package.json'),JSON.stringify({version:'1.0.0',workspaces:['packages/*']}));await writeFile(join(repo,'packages','a','package.json'),JSON.stringify({name:'a',version:'1.0.0'}));await writeFile(join(repo,'packages','b','package.json'),JSON.stringify({name:'b',version:'1.0.0',dependencies:{a:'workspace:*'}}));await git(repo,'add','-A');await git(repo,'commit','-m','feat: workspaces');await writeFile(join(repo,'packages','a','index.js'),'export default 1;\n');await git(repo,'add','-A');await git(repo,'commit','-m','feat(a): change');const detected=await detectWorkspaces(repo);assert.equal(detected.packages.length,2);const impacted=await impactedPackages(repo,'HEAD~1');assert.deepEqual(impacted.impacted.map(x=>x.name).sort(),['a','b']);assert.equal(providerCapabilities('generic').changeRequests,false);assert.equal(providerCapabilities('github').providerReleases,true);assert.deepEqual(repositoryCoordinates('git@github.com:owner/repo.git'),{provider:'github',host:'github.com',owner:'owner',repo:'repo'});}finally{await rm(base,{recursive:true,force:true});}});

test('trunk release executor versions, commits, tags, atomically pushes, journals, and verifies',async()=>{const{base,repo}=await initRepo('headbang-release-exec-');const bare=join(base,'remote.git');try{await exec('git',['init','--bare',bare]);await git(repo,'remote','add','origin',bare);await git(repo,'push','-u','origin','main');await writeFile(join(repo,'package.json'),JSON.stringify({name:'release-fixture',version:'1.0.0'},null,2));await writeFile(join(repo,'CHANGELOG.md'),'# Changelog\n\n## 2.0.0 - 2026-08-19\n\nPrepared release notes.\n');await git(repo,'add','package.json','CHANGELOG.md');await git(repo,'commit','-m','chore: add package');await git(repo,'push','origin','main');const profile={remote:'origin',permissions:{release:true,push:true},requireClean:true,requireConventionalCommits:true,branch:{strategy:'trunk',main:'main'},release:{enabled:true,tagPrefix:'v',remote:'origin',atomicPush:true,versionFiles:[{adapter:'package-json',path:'package.json'}],notes:{strategy:'headbang',changelog:'CHANGELOG.md'},providerRelease:{enabled:false},artifacts:{checksums:true,sbom:true,provenance:true}}};const config={version:2,defaultProfile:'release',profiles:{release:profile}};const plan=await releasePlan(repo,'2.0.0','release',profile,config);const result=await executeRelease(repo,'2.0.0','release',profile,config,{confirmation:plan.planDigest});assert.equal(result.status,'completed');assert.equal(JSON.parse(await readFile(join(repo,'package.json'),'utf8')).version,'2.0.0');assert.equal((await readFile(join(repo,'CHANGELOG.md'),'utf8').then(text=>text.match(/^## 2\.0\.0 /gm)?.length)),1);assert.equal((await git(repo,'rev-parse','v2.0.0^{}')).stdout.trim(),(await git(repo,'rev-parse','main')).stdout.trim());assert.ok((await exec('git',['--git-dir',bare,'show-ref','--verify','refs/tags/v2.0.0'])).stdout);const journals=await listJournals(repo);assert.ok(journals.some(x=>x.type==='release'&&x.status==='completed'));}finally{await rm(base,{recursive:true,force:true});}});

test('provider adapter contracts translate GitHub lifecycle and require review approval',async()=>{const previousFetch=globalThis.fetch,previousToken=process.env.GITHUB_TOKEN;process.env.GITHUB_TOKEN='test-token';const calls=[];globalThis.fetch=async(url,options={})=>{calls.push({url:String(url),method:options.method,body:options.body?JSON.parse(String(options.body)):null,authorization:options.headers?.authorization});return new Response(JSON.stringify({id:calls.length,ok:true}),{status:200,headers:{'content-type':'application/json'}});};try{const coordinates=repositoryCoordinates('https://github.com/owner/repo.git');await createChangeRequest(coordinates,{source:'feature/x',target:'main',title:'X'});await mergeChangeRequest(coordinates,7,'squash');await closeChangeRequest(coordinates,7);await createProviderRelease(coordinates,{tag:'v2.0.0',name:'v2.0.0'});await assert.rejects(publishReviewComment(coordinates,7,'finding',false),/explicit approval/);await publishReviewComment(coordinates,7,'finding',true);assert.equal(calls[0].url,'https://api.github.com/repos/owner/repo/pulls');assert.equal(calls[1].body.merge_method,'squash');assert.equal(calls.at(-1).url,'https://api.github.com/repos/owner/repo/issues/7/comments');assert.equal(calls[0].authorization,'Bearer test-token');}finally{globalThis.fetch=previousFetch;if(previousToken===undefined)delete process.env.GITHUB_TOKEN;else process.env.GITHUB_TOKEN=previousToken;}});

test('provider adapters use exact hosts, self-host overrides, and native change-request paths',async()=>{const previousFetch=globalThis.fetch,env={GITLAB_TOKEN:process.env.GITLAB_TOKEN,BITBUCKET_TOKEN:process.env.BITBUCKET_TOKEN,FORGEJO_TOKEN:process.env.FORGEJO_TOKEN};process.env.GITLAB_TOKEN='gitlab';process.env.BITBUCKET_TOKEN='bitbucket';process.env.FORGEJO_TOKEN='forgejo';const urls=[];globalThis.fetch=async url=>{urls.push(String(url));return new Response('{}',{status:200,headers:{'content-type':'application/json'}});};try{assert.equal(repositoryCoordinates('https://notgithub.com/o/r.git').provider,'generic');const gitlab=repositoryCoordinates('https://git.example/o/r.git','gitlab'),bitbucket=repositoryCoordinates('https://bitbucket.org/o/r.git'),forgejo=repositoryCoordinates('https://forge.example/o/r.git','forgejo');await inspectChangeRequest(gitlab,1);await inspectChangeRequest(bitbucket,2);await inspectChangeRequest(forgejo,3);assert.match(urls[0],/git\.example\/api\/v4\/projects\/o%2Fr\/merge_requests\/1$/);assert.match(urls[1],/bitbucket\.org\/2\.0\/repositories\/o\/r\/pullrequests\/2$/);assert.match(urls[2],/forge\.example\/api\/v1\/repos\/o\/r\/pulls\/3$/);await assert.rejects(mergeChangeRequest(gitlab,1,'rebase'),/does not support/);}finally{globalThis.fetch=previousFetch;for(const [key,value] of Object.entries(env))if(value===undefined)delete process.env[key];else process.env[key]=value;}});

test('projection blocks LFS pointers and limits oversized trees instead of omitting data',async()=>{const base=await mkdtemp(join(tmpdir(),'headbang-projection-v2-')),source=join(base,'source'),dest=join(base,'dest');try{await mkdir(source);await writeFile(join(source,'asset.bin'),'version https://git-lfs.github.com/spec/v1\noid sha256:abc\nsize 10\n');await assert.rejects(projectTree(source,dest,{specialObjects:'block'}),/Git LFS pointer/);await rm(dest,{recursive:true,force:true});await writeFile(join(source,'second.txt'),'x');await assert.rejects(projectTree(source,dest,{maxFiles:1}),/exceeding maxFiles/);}finally{await rm(base,{recursive:true,force:true});}});

test('plugin compatibility validation and required scanner failure are explicit',async()=>{const base=await mkdtemp(join(tmpdir(),'headbang-plugin-'));try{await writeFile(join(base,'headbang-plugin.json'),JSON.stringify({name:'fixture',version:'1.0.0',apiVersion:1,slots:['reviewAnalyzer'],entry:'index.mjs'}));await writeFile(join(base,'index.mjs'),`export default { adapters: { reviewAnalyzer: { review(){ return [] } } } };\n`);const loaded=await loadPlugin(base);assert.equal(loaded.manifest.name,'fixture');await writeFile(join(base,'headbang-plugin.json'),JSON.stringify({name:'fixture',version:'1.0.0',apiVersion:99,slots:[],entry:'index.mjs'}));await assert.rejects(loadPlugin(base),/requires API 99/);await assert.rejects(runScanner(base,{adapter:'gitleaks',required:true}),/unavailable|scanner/i);}finally{await rm(base,{recursive:true,force:true});}});

test('Git Flow keep-branch preserves the completed feature branch',async()=>{const{base,repo}=await initRepo('headbang-flow-keep-');try{const profile={...flowProfile,permissions:{flow:true,review:true}};await gitFlowInit(repo,profile);await gitFlowStart(repo,'feature','kept',profile);await writeFile(join(repo,'kept.txt'),'yes\n');await git(repo,'add','-A');await git(repo,'commit','-m','feat: kept branch');const result=await gitFlowFinish(repo,'feature','kept',profile,{version:2,profiles:{flow:profile}},{deleteBranch:false});assert.equal(result.deletedBranch,false);assert.equal((await git(repo,'show-ref','--verify','refs/heads/feature/kept')).stdout.trim().length>0,true);}finally{await rm(base,{recursive:true,force:true});}});

test('release planning rejects disabled, unpushable, invalid, and non-newer releases',async()=>{const{base,repo}=await initRepo('headbang-release-guards-');try{await writeFile(join(repo,'package.json'),JSON.stringify({name:'guarded',version:'1.2.3'}));const baseProfile={remote:'origin',permissions:{release:true,push:true},branch:{strategy:'trunk',main:'main'},release:{enabled:true}};const cfg=profile=>({version:2,profiles:{release:profile}});await assert.rejects(releasePlan(repo,'2.0.0','release',{...baseProfile,release:{enabled:false}},cfg(baseProfile)),/disabled/);await assert.rejects(releasePlan(repo,'2.0.0','release',{...baseProfile,permissions:{release:true}},cfg(baseProfile)),/push/);await assert.rejects(releasePlan(repo,'1.2.3','release',baseProfile,cfg(baseProfile)),/newer/);await assert.rejects(releasePlan(repo,'01.2.4','release',baseProfile,cfg(baseProfile)),/Invalid SemVer/);}finally{await rm(base,{recursive:true,force:true});}});

test('npm publisher packs and publishes the exact tarball through an injectable client',async()=>{const{base,repo}=await initRepo('headbang-publisher-');try{await writeFile(join(repo,'package.json'),JSON.stringify({name:'publish-fixture',version:'1.0.0'}));await git(repo,'add','package.json');await git(repo,'commit','-m','chore: package');let published=false,publishedTarget='';const result=(command,exitCode=0,stdout='',stderr='')=>({command,exitCode,stdout,stderr,durationMs:1});const client={run:async(args)=>{if(args[0]==='view')return published?result('view',0,'"1.0.0"'):result('view',1,'','E404 not found');if(args[0]==='pack'){const destination=args[args.indexOf('--pack-destination')+1],filename='publish-fixture-1.0.0.tgz';await writeFile(join(destination,filename),'exact tarball');return result('pack',0,JSON.stringify([{filename}]));}if(args[0]==='whoami')return result('whoami',0,'tester\n');if(args[0]==='publish'){published=true;publishedTarget=args[1];return result('publish',0,'+ publish-fixture@1.0.0');}throw new Error(`unexpected npm command ${args.join(' ')}`);}};const profile={remote:'origin',permissions:{publishPackage:true},packagePublish:{enabled:true,publisher:'npm',access:'public'}};const config={version:2,profiles:{npm:profile}};const plan=await planPackagePublish(repo,profile,{client});const done=await publishPackage(repo,profile,config,{confirmation:plan.planDigest,client});assert.equal(done.status,'completed');assert.equal(done.data.registryVerified,true);assert.match(publishedTarget,/publish-fixture-1\.0\.0\.tgz$/);const journal=(await listJournals(repo)).find(item=>item.type==='package-publish');assert.equal(journal.steps.every(step=>step.status==='completed'),true);}finally{await rm(base,{recursive:true,force:true});}});

test('journals reject path traversal and expose corrupt state',async()=>{const{base,repo}=await initRepo('headbang-journal-guard-');try{await assert.rejects(loadJournal(repo,'../../outside'),/Invalid operation id/);await mkdir(join(repo,'.headbang','operations'),{recursive:true});await writeFile(join(repo,'.headbang','operations','broken.json'),'{');await assert.rejects(listJournals(repo),/broken\.json/);}finally{await rm(base,{recursive:true,force:true});}});

test('projection applies limits after selection and rejects mapped collisions',async()=>{const base=await mkdtemp(join(tmpdir(),'headbang-projection-selection-')),source=join(base,'source'),dest=join(base,'dest');try{await mkdir(join(source,'keep'),{recursive:true});await mkdir(join(source,'skip'));await writeFile(join(source,'keep','a.txt'),'a');await writeFile(join(source,'skip','b.txt'),'b');const result=await projectTree(source,dest,{include:['keep/**'],maxFiles:1});assert.deepEqual(result.included,['keep/a.txt']);await rm(dest,{recursive:true,force:true});await writeFile(join(source,'skip','a.txt'),'A');await assert.rejects(projectTree(source,dest,{map:[{from:'keep',to:'same'},{from:'skip',to:'same'}]}),/collision/);}finally{await rm(base,{recursive:true,force:true});}});

test('independent monorepo planning versions impacted dependants in topological order',async()=>{const{base,repo}=await initRepo('headbang-independent-');try{await mkdir(join(repo,'packages','a'),{recursive:true});await mkdir(join(repo,'packages','b'),{recursive:true});await writeFile(join(repo,'package.json'),JSON.stringify({version:'1.0.0',workspaces:['packages/*'],headbang:{releaseMode:'independent',releaseVersions:{a:'2.0.0',b:'3.0.0'}}}));await writeFile(join(repo,'packages','a','package.json'),JSON.stringify({name:'a',version:'1.0.0'}));await writeFile(join(repo,'packages','b','package.json'),JSON.stringify({name:'b',version:'1.0.0',dependencies:{a:'^1.0.0'}}));await git(repo,'add','-A');await git(repo,'commit','-m','feat: workspaces');await writeFile(join(repo,'packages','a','index.js'),'x');await git(repo,'add','-A');await git(repo,'commit','-m','feat(a): change');const plan=await monorepoReleasePlan(repo,'9.0.0','HEAD~1');assert.deepEqual(plan.order,['a','b']);assert.deepEqual(plan.releases.map(item=>item.tag),['a@2.0.0','b@3.0.0']);await applyMonorepoVersions(repo,plan);assert.equal(JSON.parse(await readFile(join(repo,'packages','b','package.json'),'utf8')).dependencies.a,'^2.0.0');}finally{await rm(base,{recursive:true,force:true});}});

test('review includes untracked files and release notes detect BREAKING CHANGE footers',async()=>{const{base,repo}=await initRepo('headbang-review-scope-');try{await writeFile(join(repo,'untracked.txt'),'x');const profile={remote:'origin',permissions:{review:true},branch:{strategy:'trunk',main:'main'}};const review=await reviewRepo(repo,profile,{version:2,profiles:{p:profile}},{scope:'working-tree',runTasks:false});assert.ok(review.files.includes('untracked.txt'));await git(repo,'add','untracked.txt');await git(repo,'commit','-m','feat: compatible','-m','BREAKING CHANGE: contract replaced');const notes=await generateReleaseNotes(repo,'2.0.0','HEAD~1');assert.match(notes,/Breaking Changes/);}finally{await rm(base,{recursive:true,force:true});}});

test('release resume validates profile and skips every completed external step',async()=>{const{base,repo}=await initRepo('headbang-resume-');try{await git(repo,'tag','-a','v1.0.0','-m','release');const profile={remote:'origin',permissions:{release:true,push:true},branch:{strategy:'trunk',main:'main'},release:{enabled:true},packagePublish:{enabled:false,publisher:'npm'}};const config={version:2,profiles:{release:profile}},plan={profile:'release',tag:'v1.0.0',bases:{main:'main'},remote:'origin',strategy:'trunk',atomicPush:true,versionFiles:[],artifacts:{},providerRelease:{enabled:false},deliveries:[],packagePublish:null};const names=['preflight','version','notes','review','commit-and-merge','push','package-publish','artifacts','provider-release','deliveries','verify'],journal=await createJournal(repo,'release',names,plan);for(const step of journal.steps)if(step.name!=='verify')step.status='completed';journal.status='partial';await saveJournal(repo,journal);await assert.rejects(resumeRelease(repo,journal.operationId,'wrong',profile,config,planDigest(plan)),/belongs to profile/);const result=await resumeRelease(repo,journal.operationId,'release',profile,config,planDigest(plan));assert.equal(result.status,'completed');assert.equal((await loadJournal(repo,journal.operationId)).status,'completed');}finally{await rm(base,{recursive:true,force:true});}});

test('supply-chain artifacts bind file digests in checksums, SBOM, and provenance',async()=>{const{base,repo}=await initRepo('headbang-artifacts-');try{await writeFile(join(repo,'payload.tgz'),'payload');const result=await generateSupplyChainArtifacts(repo,['payload.tgz'],{checksums:true,sbom:true,provenance:true});assert.equal(result.subjects.length,1);const sums=await readFile(join(result.outputDir,'SHA256SUMS'),'utf8'),sbom=JSON.parse(await readFile(join(result.outputDir,'sbom.cdx.json'),'utf8')),provenance=JSON.parse(await readFile(join(result.outputDir,'provenance.json'),'utf8'));assert.match(sums,new RegExp(result.subjects[0].digest.sha256));assert.equal(sbom.components[0].hashes[0].content,result.subjects[0].digest.sha256);assert.equal(provenance.subject[0].digest.sha256,result.subjects[0].digest.sha256);}finally{await rm(base,{recursive:true,force:true});}});

test('delivery groups persist ordered per-destination partial state',async()=>{const{base,repo}=await initRepo('headbang-group-');try{await writeFile(join(repo,'.headbang.json'),JSON.stringify({version:2,profiles:{unused:{remote:'origin'}},deliverySets:{release:['missing']}}));const app=new HeadbangApplication(),result=await app.deliverGroup(repo,'set','release',false);assert.equal(result.status,'partial');assert.equal(result.data.results[0].profile,'missing');const journal=(await listJournals(repo)).find(item=>item.type==='delivery-set');assert.equal(journal.steps[0].status,'failed');assert.match(journal.nextActions[0],/missing/);}finally{await rm(base,{recursive:true,force:true});}});
