import { createHash } from 'node:crypto';
import { mkdir, readFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { run } from '../utils/process.js';
import type { CommandResult, HeadbangConfig, PackagePublishConfig, Profile } from '../types.js';
import { operation, planDigest, requireConfirmation } from '../domain/operation.js';
import { withOperationLock, createJournal, saveJournal } from '../operations/journal.js';
import { currentCommit, git } from '../git/git.js';
import { resolveWithin } from '../utils/path.js';

export interface PackagePublishPlan { publisher:'npm'; packagePath:string; name:string; version:string; registry:string|null; access:'public'|'restricted'; tag:string; provenance:boolean; prePublish:string[]; alreadyPublished:boolean|null; sourceSha:string|null; packageJsonSha:string }
export interface NpmClient { run(args:string[],options?:{cwd?:string;timeoutMs?:number}):Promise<CommandResult> }
const npmCommand=process.platform==='win32'?'npm.cmd':'npm';
const defaultClient:NpmClient={run:(args,options)=>run(npmCommand,args,options)};
function permission(profile:Profile){if(profile.packagePublish?.enabled!==true)throw new Error('Package publishing is disabled for this profile.');if(profile.permissions?.publishPackage!==true)throw new Error("Profile does not permit 'publishPackage'. Set it explicitly to true.");}
async function metadata(repo:string,cfg:PackagePublishConfig,versionOverride?:string){const packagePath=resolveWithin(repo,cfg.path??'.','packagePublish.path');const packageJsonPath=join(packagePath,'package.json');const bytes=await readFile(packageJsonPath);const pkg=JSON.parse(bytes.toString('utf8'));if(!pkg.name||!(versionOverride??pkg.version))throw new Error(`Package at ${packagePath} requires name and version.`);return{packagePath,name:String(pkg.name),version:String(versionOverride??pkg.version),packageJsonSha:createHash('sha256').update(bytes).digest('hex')};}
async function publishedVersion(client:NpmClient,name:string,version:string,registry?:string){if(process.env.HEADBANG_OFFLINE==='1')return null;const args=['view',`${name}@${version}`,'version','--json'];if(registry)args.push('--registry',registry);const result=await client.run(args,{timeoutMs:30000});if(result.exitCode!==0){const details=`${result.stdout}\n${result.stderr}`;if(/E404|404 Not Found|is not in this registry/i.test(details))return false;throw new Error(`Unable to verify registry state for ${name}@${version}: ${result.stderr||result.stdout}`);}try{return JSON.parse(result.stdout)===version;}catch{return result.stdout.replace(/"/g,'').trim()===version;}}

export async function planPackagePublish(repo:string,profile:Profile,options:{versionOverride?:string;sourceShaOverride?:string|null;client?:NpmClient}={}):Promise<ReturnType<typeof operation<PackagePublishPlan>>>{
  permission(profile);const cfg=profile.packagePublish!,client=options.client??defaultClient;const meta=await metadata(repo,cfg,options.versionOverride);const sourceSha=options.sourceShaOverride===undefined?await currentCommit(repo):options.sourceShaOverride;const plan:PackagePublishPlan={publisher:'npm',...meta,registry:cfg.registry??null,access:cfg.access??'public',tag:cfg.tag??'latest',provenance:cfg.provenance??false,prePublish:cfg.prePublish??[],alreadyPublished:await publishedVersion(client,meta.name,meta.version,cfg.registry),sourceSha};const digest=planDigest(plan);return operation(plan,'planned',{planDigest:digest,warnings:plan.alreadyPublished===null?['Registry state is unknown in offline mode; execution will refuse until it can verify it.']:[],nextActions:plan.alreadyPublished?[]:[`Run package publish with confirmation ${digest}`]});
}

function sameIdentity(expected:PackagePublishPlan,actual:PackagePublishPlan){for(const key of ['publisher','packagePath','name','version','registry','access','tag','provenance','packageJsonSha'] as const)if(expected[key]!==actual[key])throw new Error(`Package publication plan drifted at '${key}'. Create and confirm a new plan.`);}
export async function publishPackage(repo:string,profile:Profile,config:HeadbangConfig,options:{dryRun?:boolean;confirmation?:string;skipLock?:boolean;expectedPlan?:PackagePublishPlan;skipConfirmation?:boolean;client?:NpmClient}={}){
  const client=options.client??defaultClient;const planned=options.expectedPlan?operation(options.expectedPlan,'planned',{planDigest:planDigest(options.expectedPlan)}):await planPackagePublish(repo,profile,{client});if(options.dryRun)return planned;const digest=options.skipConfirmation?planDigest(planned.data):requireConfirmation(planned.data,options.confirmation);if(planned.data.alreadyPublished)return operation(planned.data,'already-completed',{planDigest:digest});if(planned.data.alreadyPublished===null)throw new Error('Registry state is unknown; package publication requires an online registry verification.');
  const execute=async()=>{const journal=await createJournal(repo,'package-publish',['pre-publish','pack','auth','publish','verify'],planned.data);const complete=async(index:number,detail?:unknown)=>{journal.steps[index]!.status='completed';journal.steps[index]!.detail=detail;await saveJournal(repo,journal);};try{
    if(planned.data.sourceSha&&await currentCommit(repo)!==planned.data.sourceSha)throw new Error('Repository HEAD changed after package publication was planned. Create and confirm a new plan.');
    for(const taskName of planned.data.prePublish){const def=profile.tasks?.[taskName]??config.tasks?.[taskName];if(!def)throw new Error(`Task '${taskName}' is not defined.`);const result=await run(process.platform==='win32'?'cmd':'sh',process.platform==='win32'?['/d','/s','/c',def.command]:['-lc',def.command],{cwd:def.cwd?resolveWithin(repo,def.cwd,`task '${taskName}' cwd`):repo,timeoutMs:def.timeoutMs??120000});if(result.exitCode!==0)throw new Error(`Task '${taskName}' failed.\n${result.stderr||result.stdout}`);}const current=await planPackagePublish(repo,profile,{versionOverride:planned.data.version,sourceShaOverride:planned.data.sourceSha,client});sameIdentity(planned.data,current.data);if(current.data.alreadyPublished)throw new Error(`${current.data.name}@${current.data.version} was published after planning; refusing to overwrite.`);await complete(0);
    const packDir=resolveWithin(repo,'.headbang/packages','package staging directory');await mkdir(packDir,{recursive:true});const packArgs=['pack','--json','--pack-destination',packDir];if(planned.data.registry)packArgs.push('--registry',planned.data.registry);const pack=await client.run(packArgs,{cwd:planned.data.packagePath,timeoutMs:180000});if(pack.exitCode!==0)throw new Error(`npm pack failed.\n${pack.stderr||pack.stdout}`);let filename:string;try{filename=String(JSON.parse(pack.stdout)[0].filename);}catch{throw new Error(`npm pack did not return a JSON filename: ${pack.stdout}`);}const postPack=await planPackagePublish(repo,profile,{versionOverride:planned.data.version,sourceShaOverride:planned.data.sourceSha,client});sameIdentity(planned.data,postPack.data);if(planned.data.sourceSha&&await currentCommit(repo)!==planned.data.sourceSha)throw new Error('npm pack changed repository HEAD; refusing publication.');const tarball=resolveWithin(packDir,basename(filename),'npm pack output');const tarballSha=createHash('sha256').update(await readFile(tarball)).digest('hex');await complete(1,{tarball,sha256:tarballSha});
    const authArgs=['whoami'];if(planned.data.registry)authArgs.push('--registry',planned.data.registry);const auth=await client.run(authArgs,{cwd:planned.data.packagePath,timeoutMs:30000});if(auth.exitCode!==0)throw new Error(`npm authentication failed.\n${auth.stderr||auth.stdout}`);await complete(2,{identity:auth.stdout.trim()});
    const args=['publish',tarball,'--access',planned.data.access,'--tag',planned.data.tag];if(planned.data.registry)args.push('--registry',planned.data.registry);if(planned.data.provenance)args.push('--provenance');const published=await client.run(args,{cwd:planned.data.packagePath,timeoutMs:300000});if(published.exitCode!==0)throw new Error(`npm publish failed.\n${published.stderr||published.stdout}`);await complete(3,{tarballSha});
    const verified=await publishedVersion(client,planned.data.name,planned.data.version,planned.data.registry??undefined);if(!verified)throw new Error(`Registry did not confirm ${planned.data.name}@${planned.data.version}.`);await complete(4);journal.status='completed';await saveJournal(repo,journal);return operation({...planned.data,registryVerified:true,tarball,tarballSha,stdout:published.stdout},'completed',{operationId:journal.operationId,planDigest:digest});
  }catch(error:any){const step=journal.steps.find(x=>x.status==='pending');if(step)step.status='failed';journal.status=journal.steps.some(x=>x.status==='completed')?'partial':'failed';journal.nextActions=['Inspect the journal and retry; completed registry steps will be detected.'];await saveJournal(repo,journal);throw error;}};return options.skipLock?execute():withOperationLock(repo,'package-publish',execute);
}
