#!/usr/bin/env node
import { McpServer } from '@modelcontextprotocol/server'; import { serveStdio } from '@modelcontextprotocol/server/stdio'; import * as z from 'zod/v4'; import { loadConfig,getProfile } from './config/load.js'; import { status } from './commands/status.js'; import { reviewRepo } from './review/reviewer.js'; import { previewDelivery,deliver } from './delivery.js'; import { commit } from './commands/commit.js'; import { releaseInspect } from './commands/release.js';
const text=(x:any)=>({content:[{type:'text' as const,text:JSON.stringify(x,null,2)}]});
function build(){const server=new McpServer({name:'headbang',version:'1.0.0'});
 server.registerTool('headbang_status',{description:'Inspect repository status and remotes. Read-only.',inputSchema:z.object({repo:z.string().default('.')})},async({repo})=>text(await status(repo)));
 server.registerTool('headbang_review',{description:'Run deterministic code review, branch policy checks and configured quality gates. Read-only except configured tasks may execute local build/test commands.',inputSchema:z.object({repo:z.string().default('.'),profile:z.string().optional()})},async({repo,profile})=>{const c=await loadConfig(repo);const[n,p]=getProfile(c,profile);return text({profile:n,...await reviewRepo(repo,p,c)})});
 server.registerTool('headbang_preview',{description:'Preview a policy-driven delivery without modifying Git remotes.',inputSchema:z.object({repo:z.string().default('.'),profile:z.string().optional()})},async({repo,profile})=>{const c=await loadConfig(repo);const[n,p]=getProfile(c,profile);return text(await previewDelivery(repo,n,p,c))});
 server.registerTool('headbang_deliver',{description:'Deliver a repository projection according to an explicitly configured profile. Mutates a remote only when dryRun=false and profile permissions allow it.',inputSchema:z.object({repo:z.string().default('.'),profile:z.string().optional(),dryRun:z.boolean().default(true)})},async({repo,profile,dryRun})=>{const c=await loadConfig(repo);const[n,p]=getProfile(c,profile);return text(await deliver(repo,n,p,c,{dryRun}))});
 server.registerTool('headbang_commit',{description:'Create a Conventional Commit from already staged changes, or stage all only when all=true.',inputSchema:z.object({repo:z.string().default('.'),message:z.string(),all:z.boolean().default(false)})},async({repo,message,all})=>text(await commit(repo,message,all)));

 server.registerPrompt('headbang-code-review',{title:'HEADBANG Code Review',description:'Review a HEADBANG repository using deterministic findings first, then inspect correctness, security, concurrency, error handling, tests and maintainability.',argsSchema:z.object({focus:z.string().optional()})},({focus})=>({messages:[{role:'user' as const,content:{type:'text' as const,text:`Run headbang_status and headbang_review before reviewing code. Treat deterministic failures as facts. Then review the changed code for correctness, security, race conditions, error handling, tests, API compatibility and maintainability. Prioritize actionable findings with severity, file and rationale. Do not invent issues. ${focus?`Additional focus: ${focus}`:''}`}}]}));
  server.registerTool('headbang_release_inspect',{description:'Recommend a SemVer bump from Conventional Commits. Does not publish or tag.',inputSchema:z.object({repo:z.string().default('.'),currentVersion:z.string(),profile:z.string().optional()})},async({repo,currentVersion,profile})=>{const c=await loadConfig(repo);const[,p]=getProfile(c,profile);return text(await releaseInspect(repo,currentVersion,p.release?.rules??{}))}); return server;}
const handle=serveStdio(()=>build()); console.error('HEADBANG MCP listening on stdio 🤘'); process.on('SIGINT',()=>void handle.close()); process.on('SIGTERM',()=>void handle.close());
