import { readFile, writeFile } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';
import { git } from './git/git.js';
import { resolveWithin } from './utils/path.js';

export interface WorkspacePackage { name:string; version:string; path:string; private:boolean; dependencies:string[]; deliveryProfiles:string[] }
async function packageAt(root:string,path:string){const raw=JSON.parse(await readFile(join(path,'package.json'),'utf8'));return{name:String(raw.name??relative(root,path)),version:String(raw.version??'0.0.0'),path:relative(root,path).replace(/\\/g,'/')||'.',private:Boolean(raw.private),dependencies:Object.keys({...raw.dependencies,...raw.devDependencies,...raw.peerDependencies}),deliveryProfiles:Array.isArray(raw.headbang?.deliveryProfiles)?raw.headbang.deliveryProfiles.map(String):[]} as WorkspacePackage;}
export async function detectWorkspaces(repo:string){const root=JSON.parse(await readFile(join(repo,'package.json'),'utf8'));const patterns=Array.isArray(root.workspaces)?root.workspaces:root.workspaces?.packages??[],packages:WorkspacePackage[]=[];for(const pattern of patterns){if(typeof pattern!=='string')continue;const prefix=pattern.replace(/\/\*\*?$/,'');const fs=await import('node:fs/promises');for(const entry of await fs.readdir(resolve(repo,prefix),{withFileTypes:true}).catch(()=>[])){if(entry.isDirectory()&&await fs.access(join(repo,prefix,entry.name,'package.json')).then(()=>true).catch(()=>false))packages.push(await packageAt(repo,join(repo,prefix,entry.name)));}}const duplicate=packages.find((pkg,index)=>packages.findIndex(other=>other.name===pkg.name)!==index);if(duplicate)throw new Error(`Duplicate workspace package name '${duplicate.name}'.`);return{mode:root.headbang?.releaseMode==='independent'?'independent' as const:'unified' as const,rootVersion:String(root.version??'0.0.0'),versions:(root.headbang?.releaseVersions??{}) as Record<string,string>,packages};}
export async function impactedPackages(repo:string,base='HEAD~1'){const workspace=await detectWorkspaces(repo),diff=await git(repo,['diff','--name-only',`${base}...HEAD`],true);if(diff.exitCode!==0)throw new Error(`Unable to calculate impacted workspaces: ${diff.stderr||diff.stdout}`);const files=diff.stdout.split(/\r?\n/).filter(Boolean),shared=files.some(file=>!workspace.packages.some(pkg=>file===pkg.path||file.startsWith(`${pkg.path}/`))),direct=new Set((shared?workspace.packages:workspace.packages.filter(pkg=>files.some(file=>file===pkg.path||file.startsWith(`${pkg.path}/`)))).map(pkg=>pkg.name));let changed=true;while(changed){changed=false;for(const pkg of workspace.packages)if(!direct.has(pkg.name)&&pkg.dependencies.some(dep=>direct.has(dep))){direct.add(pkg.name);changed=true;}}return{...workspace,base,files,sharedChange:shared,impacted:workspace.packages.filter(pkg=>direct.has(pkg.name))};}
export async function monorepoReleasePlan(repo:string,version:string,base='HEAD~1'){const state=await impactedPackages(repo,base);const releases=state.impacted.map(pkg=>{const nextVersion=state.mode==='unified'?version:state.versions[pkg.name];if(!nextVersion)throw new Error(`Independent monorepo release requires package.json headbang.releaseVersions['${pkg.name}'].`);return{name:pkg.name,path:pkg.path,currentVersion:pkg.version,nextVersion,tag:state.mode==='unified'?`v${version}`:`${pkg.name}@${nextVersion}`,notesScope:pkg.path,dependencies:pkg.dependencies.filter(dep=>state.impacted.some(candidate=>candidate.name===dep)),private:pkg.private,deliveryProfiles:pkg.deliveryProfiles};});return{mode:state.mode,base,files:state.files,sharedChange:state.sharedChange,releases,order:topological(releases)};}
export async function applyMonorepoVersions(repo:string,plan:{releases:Array<{name:string;path:string;nextVersion:string}>}){const changed:string[]=[];for(const item of plan.releases){const path=resolveWithin(repo,`${item.path}/package.json`.replace(/^\.\//,''),`workspace '${item.name}' package.json`),raw=JSON.parse(await readFile(path,'utf8'));raw.version=item.nextVersion;for(const field of ['dependencies','devDependencies','peerDependencies','optionalDependencies'])for(const dependency of plan.releases){if(raw[field]?.[dependency.name])raw[field][dependency.name]=`^${dependency.nextVersion}`;}await writeFile(path,`${JSON.stringify(raw,null,2)}\n`,'utf8');changed.push(relative(repo,path).replace(/\\/g,'/'));}return changed;}
function topological(items:Array<{name:string;dependencies:string[]}>){const remaining=new Map(items.map(item=>[item.name,item.dependencies])),result:string[]=[];while(remaining.size){const ready=[...remaining].filter(([,deps])=>deps.every(dep=>!remaining.has(dep)||result.includes(dep))).map(([name])=>name).sort();if(!ready.length)throw new Error(`Workspace dependency cycle: ${[...remaining.keys()].join(', ')}`);for(const name of ready){remaining.delete(name);result.push(name);}}return result;}
