import { access, copyFile, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { git, remotes } from './git/git.js';
import { detectProvider } from './providers.js';
import type { HeadbangConfig, Profile } from './types.js';
import { run } from './utils/process.js';

const exists=(path:string)=>access(path).then(()=>true).catch(()=>false);
export const PRESETS=['git-flow','github-flow','stable-backup','public-mirror','private-full-public-sanitized','monorepo-backend','release-only-mirror'] as const;
export type Preset=typeof PRESETS[number];
function baseProfile(remote:string):Profile{return{remote,permissions:{inspect:true,review:true,push:false},requireClean:true};}
export function presetConfig(preset:Preset,remote='origin',main='main'):HeadbangConfig{const base=baseProfile(remote);switch(preset){case'git-flow':return{version:2,defaultProfile:'flow',profiles:{flow:{...base,branch:{strategy:'git-flow',main,develop:'develop'},permissions:{...base.permissions,flow:false},release:{enabled:true,tagPrefix:'v'}}}};case'github-flow':return{version:2,defaultProfile:'origin',profiles:{origin:{...base,branch:{strategy:'github-flow',main},changeRequest:{enabled:true,target:main,mergeStrategy:'squash'}}}};case'public-mirror':return{version:2,defaultProfile:'public',profiles:{public:{...base,visibility:'public',history:'snapshot',projection:{exclude:['.env*','**/*.key','docs/internal/**'],specialObjects:'block'},permissions:{...base.permissions,forcePush:false}}}};case'private-full-public-sanitized':return{version:2,defaultProfile:'private',profiles:{private:{...base,visibility:'private'},public:{...base,visibility:'public',targetBranch:'public',history:'snapshot',projection:{exclude:['.env*','**/*.key','docs/internal/**'],specialObjects:'block'}}},deliverySets:{all:['private','public']}};case'monorepo-backend':return{version:2,defaultProfile:'backend',profiles:{backend:{...base,history:'snapshot',projection:{include:['backend/**'],map:[{from:'backend',to:''}]}}}};case'release-only-mirror':return{version:2,defaultProfile:'stable',profiles:{stable:{...base,sourceRef:main,targetBranch:'stable',delivery:{allowOn:['release-finish','hotfix-finish'],autoOn:['release-finish','hotfix-finish'],requireTag:true}}}};default:return{version:2,defaultProfile:'backup',profiles:{backup:{...base,sourceRef:main,targetBranch:main}}};}}
export async function detectProject(repo:string){const raw=await remotes(repo);const remoteNames=[...new Set(raw.map(line=>line.split('\t')[0]).filter(Boolean))];const remote=remoteNames.includes('origin')?'origin':remoteNames[0]??'origin';const url=raw.find(line=>line.startsWith(`${remote}\t`)&&line.endsWith('(fetch)'))?.split('\t')[1]?.replace(/ \(fetch\)$/,'')??'';const remoteHead=(await git(repo,['symbolic-ref',`refs/remotes/${remote}/HEAD`,'--short'],true)).stdout.trim();const main=(remoteHead.startsWith(`${remote}/`)?remoteHead.slice(remote.length+1):remoteHead)||(await git(repo,['branch','--show-current'])).stdout.trim()||'main';const develop=(await git(repo,['show-ref','--verify','--quiet','refs/heads/develop'],true)).exitCode===0;const files={npm:await exists(join(repo,'package-lock.json')),pnpm:await exists(join(repo,'pnpm-lock.yaml')),yarn:await exists(join(repo,'yarn.lock')),cargo:await exists(join(repo,'Cargo.toml')),python:await exists(join(repo,'pyproject.toml'))};let scripts:string[]=[];let workspaces:unknown=null;try{const pkg=JSON.parse(await readFile(join(repo,'package.json'),'utf8'));scripts=Object.keys(pkg.scripts??{});workspaces=pkg.workspaces??null;}catch{}return{remote,url,provider:url?detectProvider(url):'generic',defaultBranch:main,developExists:develop,packageManagers:Object.entries(files).filter(([,v])=>v).map(([k])=>k),scripts,monorepo:Boolean(workspaces),workspaces};}
export async function initProject(repo:string,preset:Preset,options:{write?:boolean;force?:boolean}={}){if(!PRESETS.includes(preset))throw new Error(`Unknown preset '${preset}'.`);const detected=await detectProject(repo);const config=presetConfig(preset,detected.remote,detected.defaultBranch);const path=join(repo,'.headbang.json');if(options.write){if(await exists(path)&&!options.force)throw new Error('.headbang.json already exists. Use explicit force to replace it.');await writeFile(path,`${JSON.stringify(config,null,2)}\n`,'utf8');}return{detected,preset,path,written:Boolean(options.write),config};}
export async function validateConfigFile(repo:string){const path=join(repo,'.headbang.json');const {configSchema}=await import('./config/schema.js');try{const parsed=configSchema.safeParse(JSON.parse(await readFile(path,'utf8')));return parsed.success?{valid:true,version:parsed.data.version,issues:[]}:{valid:false,version:null,issues:parsed.error.issues};}catch(error:any){return{valid:false,version:null,issues:[{code:'invalid_json',message:error?.message??String(error),path:[]}]};}}
export async function migrateConfig(repo:string,confirmed=false){if(!confirmed)throw new Error('Config migration requires explicit confirmation.');const path=join(repo,'.headbang.json'),raw=JSON.parse(await readFile(path,'utf8'));if(raw.version===2)return{status:'already-completed',path,backup:null};if(raw.version!==1)throw new Error(`Unsupported config version '${raw.version}'.`);const backup=`${path}.v1.bak`;if(await exists(backup))throw new Error(`Migration backup '${backup}' already exists; refusing to overwrite recovery data.`);const {configSchema}=await import('./config/schema.js');const candidate={...raw,version:2};const validated=configSchema.safeParse(candidate);if(!validated.success)throw new Error(`Migrated config would be invalid: ${validated.error.message}`);await copyFile(path,backup);await writeFile(path,`${JSON.stringify(candidate,null,2)}\n`,'utf8');return{status:'completed',path,backup};}
export async function credentialStatus(){const providers={github:['HEADBANG_GITHUB_TOKEN','GITHUB_TOKEN','GH_TOKEN'],gitlab:['HEADBANG_GITLAB_TOKEN','GITLAB_TOKEN'],bitbucket:['HEADBANG_BITBUCKET_TOKEN','BITBUCKET_TOKEN'],forgejo:['HEADBANG_FORGEJO_TOKEN','FORGEJO_TOKEN'],npm:['NODE_AUTH_TOKEN','NPM_TOKEN']},helper=(await run('git',['config','--global','--get','credential.helper'],{timeoutMs:5000}).catch(()=>null))?.stdout.trim()??'',commands={github:[process.platform==='win32'?'gh.exe':'gh',['auth','status']],gitlab:[process.platform==='win32'?'glab.exe':'glab',['auth','status']],bitbucket:[process.platform==='win32'?'bb.exe':'bb',['auth','status']],forgejo:[process.platform==='win32'?'tea.exe':'tea',['login','list']]} as const,cli:Record<string,boolean>={};for(const [provider,[command,args]] of Object.entries(commands)){const result=await run(command,[...args],{timeoutMs:5000}).catch(()=>null);cli[provider]=result?.exitCode===0;}return Object.fromEntries(Object.entries(providers).map(([provider,names])=>{const sources=[...names.filter(name=>Boolean(process.env[name])).map(name=>`env:${name}`),...(cli[provider]?['provider-cli']:[]),...(helper?['git-credential-helper']:[])];return[provider,{configured:names.some(name=>Boolean(process.env[name]))||Boolean(cli[provider]),available:sources.length>0,sources,credentialHelper:helper?{configured:true,kind:/manager|osxkeychain|libsecret|wincred/i.test(helper)?'os-store':'custom'}:{configured:false}}];}));}
