import type { Provider } from './types.js';
import { run } from './utils/process.js';

export interface ProviderCapabilities { provider:Provider; push:boolean; atomicPush:boolean; changeRequests:boolean; providerReleases:boolean; releaseAssets:boolean; branchProtectionRead:boolean; reviewComments:boolean }
export interface RepositoryCoordinates { provider:Provider; host:string; owner:string; repo:string }
export interface ChangeRequestInput { source:string; target:string; title:string; body?:string; draft?:boolean }
export interface ProviderReleaseInput { tag:string; name:string; body?:string; draft?:boolean; prerelease?:boolean; generatedNotes?:boolean|undefined }

function normalizedUrl(url:string){return url.replace(/^git@([^:]+):/,'https://$1/').replace(/^ssh:\/\/git@/,'https://').replace(/\.git$/,'');}
export function detectProvider(url:string):Provider{let host:string;try{host=new URL(normalizedUrl(url)).hostname.toLowerCase();}catch{return'generic';}if(host==='github.com')return'github';if(host==='gitlab.com')return'gitlab';if(host==='bitbucket.org')return'bitbucket';if(host==='codeberg.org')return'forgejo';return'generic';}
export function providerCapabilities(provider:Provider):ProviderCapabilities{const forge=provider!=='generic';return{provider,push:true,atomicPush:true,changeRequests:forge,providerReleases:provider==='github'||provider==='gitlab'||provider==='forgejo',releaseAssets:provider==='github',branchProtectionRead:forge,reviewComments:forge};}
export function repositoryCoordinates(url:string,providerOverride?:Provider):RepositoryCoordinates{const provider=providerOverride??detectProvider(url);let parsed:URL;try{parsed=new URL(normalizedUrl(url));}catch{throw new Error(`Cannot parse provider repository URL '${url}'.`);}const parts=parsed.pathname.split('/').filter(Boolean);if(parts.length<2)throw new Error(`Repository URL '${url}' does not contain owner and repository.`);return{provider,host:parsed.host,owner:parts.slice(0,-1).join('/'),repo:parts.at(-1)!};}

async function credential(c:RepositoryCoordinates){const provider=c.provider,names=provider==='github'?['HEADBANG_GITHUB_TOKEN','GITHUB_TOKEN','GH_TOKEN']:provider==='gitlab'?['HEADBANG_GITLAB_TOKEN','GITLAB_TOKEN']:provider==='bitbucket'?['HEADBANG_BITBUCKET_TOKEN','BITBUCKET_TOKEN']:provider==='forgejo'?['HEADBANG_FORGEJO_TOKEN','FORGEJO_TOKEN']:[];for(const name of names)if(process.env[name])return process.env[name]!;const filled=await run('git',['credential','fill'],{timeoutMs:5000,env:{GIT_TERMINAL_PROMPT:'0'},input:`protocol=https\nhost=${c.host}\n\n`}).catch(()=>null);if(filled?.exitCode===0){const password=filled.stdout.split(/\r?\n/).find(line=>line.startsWith('password='))?.slice(9);if(password)return password;}if(provider==='github'){const gh=await run(process.platform==='win32'?'gh.exe':'gh',['auth','token'],{timeoutMs:5000}).catch(()=>null);if(gh?.exitCode===0&&gh.stdout.trim())return gh.stdout.trim();}throw new Error(`No credential found for ${provider}. Configure ${names.join(', ')}, a Git credential helper, or an authenticated provider CLI.`);}
function apiBase(c:RepositoryCoordinates){if(c.provider==='github')return c.host==='github.com'?'https://api.github.com':`https://${c.host}/api/v3`;if(c.provider==='gitlab')return`https://${c.host}/api/v4`;if(c.provider==='bitbucket')return'https://api.bitbucket.org/2.0';if(c.provider==='forgejo')return`https://${c.host}/api/v1`;throw new Error('Generic Git remotes do not expose provider API operations.');}
export class ProviderHttpError extends Error{constructor(public status:number,message:string){super(message);this.name='ProviderHttpError';}}
async function request(c:RepositoryCoordinates,method:string,path:string,body?:unknown){const token=await credential(c);const headers:Record<string,string>={'content-type':'application/json','user-agent':'headbang/2.0'};if(c.provider==='gitlab')headers['private-token']=token;else headers.authorization=`Bearer ${token}`;const result=await fetch(`${apiBase(c)}${path}`,{method,headers,signal:AbortSignal.timeout(30000),...(body===undefined?{}:{body:JSON.stringify(body)})});const text=await result.text();let data:unknown=text;try{data=text?JSON.parse(text):null;}catch{}if(!result.ok)throw new ProviderHttpError(result.status,`${c.provider} API ${method} ${path} failed (${result.status}): ${typeof data==='object'?JSON.stringify(data):text}`);return data;}
const encoded=(value:string)=>encodeURIComponent(value);
function repoPath(c:RepositoryCoordinates){return c.provider==='gitlab'?`/projects/${encoded(`${c.owner}/${c.repo}`)}`:c.provider==='bitbucket'?`/repositories/${c.owner}/${c.repo}`:`/repos/${c.owner}/${c.repo}`;}

export async function createChangeRequest(c:RepositoryCoordinates,input:ChangeRequestInput){if(!providerCapabilities(c.provider).changeRequests)throw new Error(`${c.provider} does not support change requests.`);const base=repoPath(c);if(c.provider==='gitlab')return request(c,'POST',`${base}/merge_requests`,{source_branch:input.source,target_branch:input.target,title:input.title,description:input.body,remove_source_branch:false,draft:input.draft});if(c.provider==='bitbucket')return request(c,'POST',`${base}/pullrequests`,{title:input.title,description:input.body,source:{branch:{name:input.source}},destination:{branch:{name:input.target}},close_source_branch:false});return request(c,'POST',`${base}/pulls`,{head:input.source,base:input.target,title:input.title,body:input.body,draft:input.draft});}
export async function inspectChangeRequest(c:RepositoryCoordinates,id:number){const suffix=c.provider==='gitlab'?`merge_requests/${id}`:c.provider==='bitbucket'?`pullrequests/${id}`:`pulls/${id}`;return request(c,'GET',`${repoPath(c)}/${suffix}`);}
export async function listChangeRequestChecks(c:RepositoryCoordinates,id:number){const base=repoPath(c);if(c.provider==='github'){const cr:any=await inspectChangeRequest(c,id);const sha=cr.head?.sha;if(!sha)throw new Error(`GitHub change request ${id} did not include a head SHA.`);return request(c,'GET',`${base}/commits/${sha}/check-runs`);}if(c.provider==='gitlab')return request(c,'GET',`${base}/merge_requests/${id}/pipelines`);if(c.provider==='bitbucket')return request(c,'GET',`${base}/pullrequests/${id}/statuses`);return request(c,'GET',`${base}/pulls/${id}/commits`);}
export async function listChangeRequestReviewers(c:RepositoryCoordinates,id:number){const base=repoPath(c);if(c.provider==='github')return request(c,'GET',`${base}/pulls/${id}/requested_reviewers`);if(c.provider==='gitlab'||c.provider==='bitbucket')return inspectChangeRequest(c,id);return request(c,'GET',`${base}/pulls/${id}/reviews`);}
export async function mergeChangeRequest(c:RepositoryCoordinates,id:number,strategy:'merge'|'squash'|'rebase'|'fast-forward'='merge'){const base=repoPath(c);if(c.provider==='gitlab'){if(strategy==='rebase'||strategy==='fast-forward')throw new Error(`GitLab adapter does not support requested merge strategy '${strategy}'.`);return request(c,'PUT',`${base}/merge_requests/${id}/merge`,{squash:strategy==='squash',merge_when_pipeline_succeeds:false});}if(c.provider==='bitbucket')return request(c,'POST',`${base}/pullrequests/${id}/merge`,{merge_strategy:strategy==='fast-forward'?'fast_forward':strategy});return request(c,'PUT',`${base}/pulls/${id}/merge`,{merge_method:strategy==='fast-forward'?'rebase':strategy});}
export async function closeChangeRequest(c:RepositoryCoordinates,id:number){const base=repoPath(c);if(c.provider==='gitlab')return request(c,'PUT',`${base}/merge_requests/${id}`,{state_event:'close'});if(c.provider==='bitbucket')return request(c,'POST',`${base}/pullrequests/${id}/decline`);return request(c,'PATCH',`${base}/pulls/${id}`,{state:'closed'});}
export async function branchProtection(c:RepositoryCoordinates,branch:string){if(!providerCapabilities(c.provider).branchProtectionRead)throw new Error(`${c.provider} cannot inspect branch protection.`);const base=repoPath(c);if(c.provider==='gitlab')return request(c,'GET',`${base}/protected_branches/${encoded(branch)}`);if(c.provider==='bitbucket')return request(c,'GET',`${base}/branch-restrictions?q=pattern=${encoded(`"${branch}"`)}`);return request(c,'GET',`${base}/branches/${encoded(branch)}/protection`);}
export async function publishReviewComment(c:RepositoryCoordinates,id:number,body:string,approved:boolean){if(!approved)throw new Error('Publishing review findings requires explicit approval.');const base=repoPath(c);if(c.provider==='gitlab')return request(c,'POST',`${base}/merge_requests/${id}/notes`,{body});if(c.provider==='bitbucket')return request(c,'POST',`${base}/pullrequests/${id}/comments`,{content:{raw:body}});return request(c,'POST',`${base}/issues/${id}/comments`,{body});}
export async function createProviderRelease(c:RepositoryCoordinates,input:ProviderReleaseInput){if(!providerCapabilities(c.provider).providerReleases)throw new Error(`${c.provider} does not support provider releases.`);const base=repoPath(c);if(c.provider==='gitlab')return request(c,'POST',`${base}/releases`,{tag_name:input.tag,name:input.name,description:input.body});return request(c,'POST',`${base}/releases`,{tag_name:input.tag,name:input.name,body:input.body,draft:input.draft,prerelease:input.prerelease,generate_release_notes:input.generatedNotes??false});}
export async function inspectProviderRelease(c:RepositoryCoordinates,tag:string){if(!providerCapabilities(c.provider).providerReleases)throw new Error(`${c.provider} does not support provider releases.`);return request(c,'GET',`${repoPath(c)}/releases/${c.provider==='github'?`tags/${encoded(tag)}`:encoded(tag)}`);}
export async function uploadProviderReleaseAssets(c:RepositoryCoordinates,release:any,assets:Array<{name:string;data:Uint8Array}>){if(!assets.length)return[];if(!providerCapabilities(c.provider).releaseAssets)throw new Error(`${c.provider} adapter does not support binary release-asset upload; no assets were silently omitted.`);const token=await credential(c),template=String(release.upload_url??'');if(!template)throw new Error('Provider release response did not include an asset upload URL.');const base=template.replace(/\{.*$/,'');const results=[];for(const asset of assets){const response=await fetch(`${base}?name=${encoded(asset.name)}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/octet-stream','user-agent':'headbang/2.0'},signal:AbortSignal.timeout(60000),body:Buffer.from(asset.data) as unknown as BodyInit});const text=await response.text();if(!response.ok)throw new ProviderHttpError(response.status,`Asset upload '${asset.name}' failed (${response.status}): ${text}`);let parsed:unknown=text;try{parsed=text?JSON.parse(text):null;}catch{}results.push(parsed);}return results;}
