import { readFile, writeFile } from 'node:fs/promises';
import { relative } from 'node:path';
import type { HeadbangConfig, Profile } from '../types.js';
import { git, currentBranch, currentCommit, isClean, remoteUrl } from '../git/git.js';
import { releasePlan } from './planner.js';
import { generateReleaseNotes } from './notes.js';
import { requireConfirmation, operation } from '../domain/operation.js';
import { createJournal, listJournals, loadJournal, saveJournal, withOperationLock, type Journal } from '../operations/journal.js';
import { reviewRepo } from '../review/reviewer.js';
import { gitFlowFinish } from '../workflow.js';
import { createProviderRelease, inspectProviderRelease, ProviderHttpError, repositoryCoordinates, uploadProviderReleaseAssets } from '../providers.js';
import { planPackagePublish, publishPackage, type PackagePublishPlan } from '../packages/publisher.js';
import { generateSupplyChainArtifacts } from '../artifacts.js';
import { resolveWithin } from '../utils/path.js';
import { deliver } from '../delivery.js';
import { applyMonorepoVersions } from '../monorepo.js';

async function writeVersion(repo:string,file:{adapter:string;path:string;jsonPath?:string},version:string){const path=resolveWithin(repo,file.path,'release version file');let raw:any;try{raw=JSON.parse(await readFile(path,'utf8'));}catch(error:any){if(error?.code==='ENOENT')throw new Error(`Configured version file '${file.path}' does not exist.`);throw error;}if(file.adapter==='package-json'){raw.version=version;if(raw.packages?.[''])raw.packages[''].version=version;}else{const parts=(file.jsonPath??'version').split('.');let cursor=raw;for(const part of parts.slice(0,-1)){cursor[part]??={};cursor=cursor[part];}cursor[parts.at(-1)!]=version;}await writeFile(path,`${JSON.stringify(raw,null,2)}\n`,'utf8');}
async function prependChangelog(repo:string,path:string,notes:string){const full=resolveWithin(repo,path,'release changelog');const current=await readFile(full,'utf8').catch(()=> '# Changelog\n');const heading=notes.split(/\r?\n/,1)[0]??'';if(heading&&current.split(/\r?\n/).includes(heading))return;const marker='# Changelog';const body=current.startsWith(marker)?current.slice(marker.length).trimStart():current;await writeFile(full,`${marker}\n\n${notes}\n\n${body}`.trimEnd()+'\n','utf8');}
async function refExists(repo:string,type:'heads'|'tags',name:string){return(await git(repo,['show-ref','--verify','--quiet',`refs/${type}/${name}`],true)).exitCode===0;}
function packageIntent(expected:PackagePublishPlan,actual:PackagePublishPlan){for(const key of ['publisher','packagePath','name','version','registry','access','tag','provenance'] as const)if(expected[key]!==actual[key])throw new Error(`Embedded package plan drifted at '${key}'. Create and confirm a new release plan.`);}
function bindJournal(repo:string,journal:Journal){Object.defineProperty(journal,'__repo',{value:repo,enumerable:false});return journal;}
async function complete(journal:Journal,name:string,detail?:unknown){const step=journal.steps.find(item=>item.name===name);if(!step)throw new Error(`Journal step '${name}' is missing.`);step.status='completed';if(detail!==undefined)step.detail=detail;await saveJournal((journal as any).__repo,journal);}
async function pushReleaseRefs(repo:string,remote:string,refs:string[],atomic:boolean,journal:Journal){const pushed=await git(repo,['push',...(atomic?['--atomic']:[]),remote,...refs],true);if(pushed.exitCode===0)return pushed;const evidence=Object.fromEntries(await Promise.all(refs.map(async ref=>{const state=await git(repo,['ls-remote',remote,`refs/heads/${ref}`,`refs/tags/${ref}`,`refs/tags/${ref}^{}`],true);return[ref,state.exitCode===0?state.stdout.trim():`inspection failed: ${state.stderr||state.stdout}`];})));const step=journal.steps.find(item=>item.name==='push')!;step.status='failed';step.detail={atomic,refs,evidence,error:pushed.stderr||pushed.stdout};journal.status=journal.steps.some(item=>item.status==='completed')?'partial':'failed';await saveJournal(repo,journal);throw new Error(`Release push failed; journal records per-ref remote evidence. ${pushed.stderr||pushed.stdout}`);}

export async function executeRelease(repo:string,version:string,profileName:string,profile:Profile,config:HeadbangConfig,options:{confirmation?:string;dryRun?:boolean}={}){
  const planned=await releasePlan(repo,version,profileName,profile,config);if(options.dryRun)return planned;const digest=requireConfirmation(planned.data,options.confirmation);
  if(await refExists(repo,'tags',planned.data.tag)){const prior=(await listJournals(repo)).find(item=>item.type==='release'&&(item.context as any)?.tag===planned.data.tag);if(prior?.status==='completed')return operation(planned.data,'already-completed',{operationId:prior.operationId,planDigest:digest});throw new Error(`Tag '${planned.data.tag}' already exists but no completed release journal matches it. Resume or repair explicitly; HEADBANG will not overwrite it.`);}
  if(!(await isClean(repo)))throw new Error('Working tree must be clean before release execution.');
  return withOperationLock(repo,'release',async()=>{const journal=bindJournal(repo,await createJournal(repo,'release',['preflight','version','notes','review','commit-and-merge','push','package-publish','artifacts','provider-release','deliveries','verify'],planned.data));try{
    const branch=await currentBranch(repo),expected=planned.data.strategy==='git-flow'?`release/${planned.data.proposedVersion}`:planned.data.bases.main;if(branch!==expected)throw new Error(`Release execution requires branch '${expected}', current branch is '${branch}'.`);if(await currentCommit(repo)!==planned.data.sourceSha)throw new Error('HEAD changed after planning; create and confirm a new release plan.');for(const [name,sha] of Object.entries(planned.data.baseShas)){if((await git(repo,['rev-parse',name])).stdout.trim()!==sha)throw new Error(`Local branch '${name}' changed after planning.`);}const remote=planned.data.remote;if(await remoteUrl(repo,remote)!==planned.data.remoteRepository)throw new Error(`Remote '${remote}' URL changed after planning; create and confirm a new release plan.`);await git(repo,['fetch',remote,'--tags']);for(const [name,sha] of Object.entries(planned.data.remoteShas)){const result=await git(repo,['rev-parse',`refs/remotes/${remote}/${name}`],true),actual=result.exitCode===0?result.stdout.trim():null;if(actual!==sha)throw new Error(`Remote branch '${name}' changed after planning; create a new plan.`);}await complete(journal,'preflight',{sourceSha:planned.data.sourceSha,baseShas:planned.data.baseShas,remoteShas:planned.data.remoteShas,remoteRepository:planned.data.remoteRepository});
    for(const file of planned.data.versionFiles)await writeVersion(repo,file,planned.data.proposedVersion);const workspaceFiles=planned.data.monorepo?await applyMonorepoVersions(repo,planned.data.monorepo):[];await complete(journal,'version',{workspaceFiles});
    const last=(await git(repo,['describe','--tags','--abbrev=0'],true)).stdout.trim();const notes=await generateReleaseNotes(repo,planned.data.proposedVersion,last||undefined);if(planned.data.notes.strategy==='headbang'&&planned.data.notes.changelog)await prependChangelog(repo,planned.data.notes.changelog,notes);await complete(journal,'notes',{notes});
    const review=await reviewRepo(repo,{...profile,requireClean:false},config,{enforceBranchPolicy:false,scope:'working-tree'});const blockers=review.findings.filter(f=>planned.data.blockOn.includes(f.severity as any));if(blockers.length)throw new Error(`Release review blocked: ${blockers.map(x=>x.message).join('; ')}`);await complete(journal,'review',{findingCount:review.findings.length});
    const staged=[...new Set([...planned.data.versionFiles.map((x:{path:string})=>x.path),...workspaceFiles,...(planned.data.notes.strategy==='headbang'&&planned.data.notes.changelog?[planned.data.notes.changelog]:[])])];await git(repo,['add','--',...staged]);await git(repo,['commit','-m',`chore(release): ${planned.data.proposedVersion}`]);let flowResult:unknown=null;if(planned.data.strategy==='git-flow')flowResult=await gitFlowFinish(repo,'release',planned.data.proposedVersion,profile,config,{review:false});else await git(repo,['tag','-a',planned.data.tag,'-m',`Release ${planned.data.tag}`]);const releaseTags=[...new Set([planned.data.tag,...(planned.data.monorepo?.releases.map((item:any)=>item.tag)??[])])];for(const tag of releaseTags)if(!(await refExists(repo,'tags',tag)))await git(repo,['tag','-a',tag,planned.data.bases.main,'-m',`Release ${tag}`]);await complete(journal,'commit-and-merge',{flowResult,releaseTags});
    const refs=(planned.data.strategy==='git-flow'?[planned.data.bases.main,planned.data.bases.develop,...releaseTags]:[planned.data.bases.main,...releaseTags]).filter((x):x is string=>Boolean(x));const pushed=await pushReleaseRefs(repo,remote,refs,planned.data.atomicPush,journal);await complete(journal,'push',{refs,output:pushed.stdout||pushed.stderr});
    const packageResults:any[]=[];if(planned.data.packagePublish){const live=await planPackagePublish(repo,profile);packageIntent(planned.data.packagePublish as PackagePublishPlan,live.data);packageResults.push(await publishPackage(repo,profile,config,{expectedPlan:live.data,skipConfirmation:true,skipLock:true}));}for(const expected of planned.data.monorepo?.packagePlans??[]){const path=relative(repo,expected.packagePath).replace(/\\/g,'/'),workspaceProfile={...profile,packagePublish:{...profile.packagePublish!,path,workspaces:false}};const live=await planPackagePublish(repo,workspaceProfile);packageIntent(expected,live.data);packageResults.push(await publishPackage(repo,workspaceProfile,config,{expectedPlan:live.data,skipConfirmation:true,skipLock:true}));}const packageResult=packageResults.length===1?packageResults[0]:packageResults;await complete(journal,'package-publish',packageResults.map(result=>({operationId:result.operationId,tarball:result.data?.tarball,tarballSha:result.data?.tarballSha})));
    const artifactInputs=planned.data.versionFiles.map((x:{path:string})=>x.path);for(const result of packageResults)if(result.data?.tarball)artifactInputs.push(relative(repo,result.data.tarball));const artifacts=await generateSupplyChainArtifacts(repo,artifactInputs,planned.data.artifacts);await complete(journal,'artifacts',artifacts);
    let providerRelease:unknown=null;if(planned.data.providerRelease.enabled){const coordinates=repositoryCoordinates(await remoteUrl(repo,remote),profile.provider);const created:any=await createProviderRelease(coordinates,{tag:planned.data.tag,name:planned.data.tag,body:notes,...(planned.data.providerRelease.draft===undefined?{}:{draft:planned.data.providerRelease.draft}),prerelease:planned.data.prerelease,generatedNotes:planned.data.providerRelease.generatedNotes});const requested:string[]=planned.data.providerRelease.assets??[];const generated:string[]=artifacts.generated??[];const paths=[...new Set([...requested.map((x:string)=>resolveWithin(repo,x,'release asset')),...generated])];const assets=await Promise.all(paths.map(async path=>({name:path.split(/[\\/]/).at(-1)!,data:new Uint8Array(await readFile(path))})));const uploaded=await uploadProviderReleaseAssets(coordinates,created,assets);providerRelease={created,uploaded};}await complete(journal,'provider-release',providerRelease);
    const deliveries=[];const deliveryNames=[...new Set([...planned.data.deliveries.map((item:any)=>item.profile),...(planned.data.monorepo?.releases.flatMap((item:any)=>item.deliveryProfiles??[])??[])])];for(const profileName of deliveryNames){const target=config.profiles[profileName];if(target)deliveries.push(await deliver(repo,profileName,target,config,{context:{event:'release-finish',sourceRef:planned.data.bases.main,tag:planned.data.tag}}));}await complete(journal,'deliveries',deliveries);
    const tagSha=(await git(repo,['rev-parse',`${planned.data.tag}^{}`])).stdout.trim(),mainSha=(await git(repo,['rev-parse',planned.data.bases.main])).stdout.trim();if(tagSha!==mainSha)throw new Error(`Tag ${planned.data.tag} does not resolve to ${planned.data.bases.main}.`);const remoteTag=(await git(repo,['ls-remote',remote,`refs/tags/${planned.data.tag}^{}`])).stdout.trim().split(/\s+/)[0];if(remoteTag!==tagSha)throw new Error(`Remote did not confirm annotated tag ${planned.data.tag}.`);await complete(journal,'verify',{tagSha,remoteTag});journal.status='completed';journal.nextActions=[];await saveJournal(repo,journal);return operation({plan:planned.data,flowResult,push:pushed.stdout||pushed.stderr,providerRelease,packageResult,artifacts,deliveries,tagSha},'completed',{operationId:journal.operationId,planDigest:digest});
  }catch(error:any){const step=journal.steps.find(x=>x.status==='pending');if(!journal.steps.some(x=>x.status==='failed')&&step)step.status='failed';journal.status=journal.steps.some(x=>x.status==='completed')?'partial':'failed';journal.nextActions=['Inspect operation state and run headbang resume after correcting the reported failure.'];await saveJournal(repo,journal);throw error;}});
}

export async function resumeRelease(repo:string,operationId:string,profileName:string,profile:Profile,config:HeadbangConfig,confirmation?:string){const journal=await loadJournal(repo,operationId);if(journal.type!=='release')throw new Error(`Operation '${operationId}' is not a release.`);if(journal.status==='completed')return operation(journal,'already-completed',{operationId});const plan=journal.context as any;if(plan.profile!==profileName)throw new Error(`Operation '${operationId}' belongs to profile '${plan.profile}', not '${profileName}'.`);requireConfirmation(plan,confirmation);const localNames=['preflight','version','notes','review','commit-and-merge'];if(journal.steps.some(step=>localNames.includes(step.name)&&step.status!=='completed'))throw new Error('This release stopped before local Git mutation completed. HEADBANG cannot prove an automatic replay is safe; inspect the journal and restart deliberately.');return withOperationLock(repo,'release-resume',async()=>{const done=async(name:string,detail?:unknown)=>complete(journal,name,detail);try{const remote=plan.remote;const step=(name:string)=>journal.steps.find(x=>x.name===name)!;if(step('push').status!=='completed'){const tags=[...new Set([plan.tag,...(plan.monorepo?.releases?.map((item:any)=>item.tag)??[])])];const refs=(plan.strategy==='git-flow'?[plan.bases.main,plan.bases.develop,...tags]:[plan.bases.main,...tags]).filter(Boolean);await git(repo,['push',...(plan.atomicPush?['--atomic']:[]),remote,...refs]);await done('push',{refs});}
    if(step('package-publish').status!=='completed'){
      const results:any[]=[];
      if(plan.packagePublish){const live=await planPackagePublish(repo,profile);packageIntent(plan.packagePublish,live.data);results.push(await publishPackage(repo,profile,config,{expectedPlan:live.data,skipConfirmation:true,skipLock:true}));}
      for(const expected of plan.monorepo?.packagePlans??[]){const path=relative(repo,expected.packagePath).replace(/\\/g,'/'),workspaceProfile={...profile,packagePublish:{...profile.packagePublish!,path,workspaces:false}};const live=await planPackagePublish(repo,workspaceProfile);packageIntent(expected,live.data);results.push(await publishPackage(repo,workspaceProfile,config,{expectedPlan:live.data,skipConfirmation:true,skipLock:true}));}
      await done('package-publish',results.map(result=>({operationId:result.operationId,tarball:result.data?.tarball,tarballSha:result.data?.tarballSha})));
    }
    let artifacts:any=step('artifacts').detail;if(step('artifacts').status!=='completed'){const inputs=plan.versionFiles.map((x:any)=>x.path),packageDetails:any[]=Array.isArray(step('package-publish').detail)?step('package-publish').detail as any[]:[step('package-publish').detail];for(const detail of packageDetails)if(detail?.tarball)inputs.push(relative(repo,detail.tarball));artifacts=await generateSupplyChainArtifacts(repo,inputs,plan.artifacts);await done('artifacts',artifacts);}
    if(step('provider-release').status!=='completed'){
      let providerRelease=null;
      if(plan.providerRelease.enabled){
        const coordinates=repositoryCoordinates(await remoteUrl(repo,remote),profile.provider);let existing:unknown;try{existing=await inspectProviderRelease(coordinates,plan.tag);}catch(error){if(error instanceof ProviderHttpError&&error.status===404)existing=null;else throw error;}const notes=(step('notes').detail as any)?.notes??'';
        const created:any=existing??await createProviderRelease(coordinates,{tag:plan.tag,name:plan.tag,body:notes,draft:plan.providerRelease.draft,prerelease:plan.prerelease,generatedNotes:plan.providerRelease.generatedNotes});
        const paths=[...new Set([...(plan.providerRelease.assets??[]).map((x:string)=>resolveWithin(repo,x,'release asset')),...(artifacts?.generated??[])])];
        const existingAssets=new Set((created.assets??[]).map((asset:any)=>String(asset.name)));
        const assets=await Promise.all(paths.filter(path=>!existingAssets.has(path.split(/[\\/]/).at(-1)!)).map(async path=>({name:path.split(/[\\/]/).at(-1)!,data:new Uint8Array(await readFile(path))})));
        providerRelease={created,uploaded:await uploadProviderReleaseAssets(coordinates,created,assets)};
      }
      await done('provider-release',providerRelease);
    }
    if(step('deliveries').status!=='completed'){const results=[],names=[...new Set([...plan.deliveries.map((item:any)=>item.profile),...(plan.monorepo?.releases.flatMap((item:any)=>item.deliveryProfiles??[])??[])])];for(const name of names){const target=config.profiles[name as string];if(target)results.push(await deliver(repo,name as string,target,config,{context:{event:'release-finish',sourceRef:plan.bases.main,tag:plan.tag}}));}await done('deliveries',results);}
    const tagSha=(await git(repo,['rev-parse',`${plan.tag}^{}`])).stdout.trim(),mainSha=(await git(repo,['rev-parse',plan.bases.main])).stdout.trim();if(tagSha!==mainSha)throw new Error(`Tag ${plan.tag} does not resolve to ${plan.bases.main}.`);await done('verify',{tagSha});journal.status='completed';journal.nextActions=[];await saveJournal(repo,journal);return operation(journal,'completed',{operationId});}catch(error){journal.status='partial';await saveJournal(repo,journal);throw error;}});}
